version: '3.8'

services:
  dev-app:
    container_name: dev-app
    restart: always
    build: . 
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgres/data 
    restart: always
    env_file:
      - .env
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: none
    restart: unless-stopped
volumes:
  db:
  pgadmin-data:
